name: Build Kivy APK

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git openjdk-8-jdk python3-pip autoconf automake libtool
          python3 -m pip install --upgrade pip
          pip install python-for-android

      - name: Build APK
        run: |
          python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch=armeabi-v7a
          python3 -m pythonforandroid.toolchain build --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch=armeabi-v7a
          python3 -m pythonforandroid.toolchain apk --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch=armeabi-v7a

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: loader-apk
          path: app/build/outputs/apk/debug/*.apk
