name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git \
            openjdk-8-jdk \
            python3-pip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            build-essential \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libbz2-dev \
            libreadline-dev \
            libncurses5-dev \
            libgdbm-dev \
            liblzma-dev
          python3 -m pip install --upgrade pip
          pip install python-for-android

      - name: Build APK
        run: |
          python3 -m pythonforandroid.toolchain create --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch=armeabi-v7a
          python3 -m pythonforandroid.toolchain build --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch=armeabi-v7a
          python3 -m pythonforandroid.toolchain apk --dist_name=myapp --bootstrap=sdl2 --requirements=python3,kivy --arch=armeabi-v7a

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: loader-apk
          path: app/build/outputs/apk/debug/*.apk
